require("daemons.battery")
require("daemons.network")
require("daemons.volume")
require("daemons.playerctl")
require("daemons.cpu")
require("daemons.memory")
require("daemons.brightness")
require("daemons.uptime")
